version: "3.9"

services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data

  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn YOURPROJECT.wsgi:application -b 0.0.0.0:8000 --workers 2"
    env_file: .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      SQLITE_PATH: /data/db.sqlite3
    volumes:
      - sqlite_data:/data
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A YOURPROJECT worker -l info
    env_file: .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      SQLITE_PATH: /data/db.sqlite3
    volumes:
      - sqlite_data:/data
    depends_on:
      - redis
      - web

  beat:
    build: .
    command: celery -A YOURPROJECT beat -l info
    env_file: .env
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      SQLITE_PATH: /data/db.sqlite3
    volumes:
      - sqlite_data:/data
    depends_on:
      - redis
      - web

volumes:
  sqlite_data:
  redis_data:
